### ISSUE TITLE
Find a way to support updates from a HA list item

### ISSUE THREAD

**Issue by SavageCore** [SavageCore/HA_Addons#1]
The event `shopping_list_updated` gives this output on an update:

```yaml
event_type: shopping_list_updated
data:
  action: update
  item:
    name: Milk Updated
    id: "8143486231"
    complete: false
origin: LOCAL
time_fired: "2024-08-18T13:48:49.539623+00:00"
context:
  id: 01J5JVYV039W7C7TDRQZ2R11Y0
  parent_id: null
  user_id: null
  ```
  
  My "api" for the add-on wants the existing name and the new name to update Alexa list.
  
  ```python
  @app.route("/update_item", methods=["PUT"])
def update_item_route():
    item = request.json.get("item")
    new_item = request.json.get("new_item")
    if update_shopping_list_item(driver, item, new_item):
        return jsonify(
            {
                "status": "success",
                "message": f"Updated '{item}' to '{new_item}' in HA shopping list",
            }
        )
    else:
        return jsonify(
            {"status": "failure", "message": f"'{item}' not found in HA shopping list"}
        )
```
  
  
  ```python
  def update_shopping_list_item(driver: Driver, item: str, new_item: str) -> bool:
    """Update an item in the shopping list."""
    driver.get(config["list_url"])
    shopping_list_items = driver.find_elements(
        By.CSS_SELECTOR, ".virtual-list .item-title"
    )
    item_found = False

    for shopping_list_item in shopping_list_items:
        if shopping_list_item.text == item:
            item_found = True
            inner_div = shopping_list_item
            while inner_div.get_attribute("class") != "inner":
                inner_div = inner_div.find_element(By.XPATH, "..")
            edit_button = inner_div.find_element(
                By.CSS_SELECTOR, ".item-actions-1 button"
            )
            edit_button.click()
            edit_item_input = driver.find_element(By.CSS_SELECTOR, ".input-box input")
            edit_item_input.clear()
            edit_item_input.send_keys(new_item)
            update_button = driver.find_element(
                By.CSS_SELECTOR, ".item-actions-2 button"
            )
            update_button.click()
            break

    return item_found
    ```
