### ISSUE TITLE
not able to find rest command

### ISSUE THREAD

**Issue by shedman214** [SavageCore/HA_Addons#28]
I have completed the steps to set up the amazon shopping list but for the automation. I cannot find the rest command to add or update the shopping list 
![image](https://github.com/user-attachments/assets/f4a2d27a-981c-4c9f-885d-5bd266ca3aa0)

**Comment by SavageCore** [comment]
I will update the readme soon but you need to add the `rest_command` block from https://github.com/SavageCore/HA_Addons/tree/main/alexa_shopping_list_sync#home-assistant-setup to your main config, then you can setup automations.yml

**Comment by shedman214** [comment]
> I will update the readme soon but you need to add the `rest_command` block from https://github.com/SavageCore/HA_Addons/tree/main/alexa_shopping_list_sync#home-assistant-setup to your main config, then you can setup automations.yml

Would this be what I add to my config.yaml

```
name: "Alexa Shopping List Sync"
description: "Sync your Alexa Shopping List with Home Assistant"
version: "0.1.7"
slug: "alexa_shopping_list_sync"
init: false
url: "https://github.com/SavageCore/HA_Addons/tree/main/alexa_shopping_list_sync"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
ports:
  5000/tcp: 5000
options:
  email: "joe.bloggs@example.com"
  password: "hunter2"
  mfa_secret: "OTP Secret"
  login_url: "https://www.amazon.co.uk/ap/signin?openid.pape.max_auth_age=3600&openid.return_to=https%3A%2F%2Fwww.amazon.co.uk%2Falexaquantum%2Fsp%2FalexaShoppingList&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_alexa_quantum_uk&openid.mode=checkid_setup&language=en_GB&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0"
  list_url: "https://www.amazon.co.uk/alexaquantum/sp/alexaShoppingList"
  ha_token: ""
  ha_url: "ws://homeassistant.local:8123/api/websocket"
schema:
  email: str
  password: password
  mfa_secret: password
  login_url: str
  list_url: str
  ha_token: str
  ha_url: str
```

**Comment by SavageCore** [comment]
@shedman214 No, within `configuration.yaml` (the main HA config) add this block:

```yaml
rest_command:
  add_shopping_list_item:
    url: "http://localhost:5000/add_item"
    method: post
    payload: '{"item": "{{ item }}"}'
    headers:
      Content-Type: application/json

  update_shopping_list_item:
    url: "http://localhost:5000/update_item"
    method: put
    payload: '{"item": "{{ item }}", "new_item": "{{ new_item }}"}'
    headers:
      Content-Type: application/json

  complete_shopping_list_item:
    url: "http://localhost:5000/complete_item"
    method: put
    payload: '{"item": "{{ item }}"}'
    headers:
      Content-Type: application/json

  remove_shopping_list_item:
    url: "http://localhost:5000/remove_item"
    method: post
    payload: '{"item": "{{ item }}"}'
    headers:
      Content-Type: application/json
  ```
  
  This defines the rest commands to be used by the automations

**Comment by shedman214** [comment]
> @shedman214 No, within `configuration.yaml` (the main HA config) add this block:
> 
> ```yaml
> rest_command:
>   add_shopping_list_item:
>     url: "http://localhost:5000/add_item"
>     method: post
>     payload: '{"item": "{{ item }}"}'
>     headers:
>       Content-Type: application/json
> 
>   update_shopping_list_item:
>     url: "http://localhost:5000/update_item"
>     method: put
>     payload: '{"item": "{{ item }}", "new_item": "{{ new_item }}"}'
>     headers:
>       Content-Type: application/json
> 
>   complete_shopping_list_item:
>     url: "http://localhost:5000/complete_item"
>     method: put
>     payload: '{"item": "{{ item }}"}'
>     headers:
>       Content-Type: application/json
> 
>   remove_shopping_list_item:
>     url: "http://localhost:5000/remove_item"
>     method: post
>     payload: '{"item": "{{ item }}"}'
>     headers:
>       Content-Type: application/json
> ```
> 
> This defines the rest commands to be used by the automations

@SavageCore do I change "localhost" or leave it?

**Comment by SavageCore** [comment]
Yes, leave it as it is. That connects to the internal server started by the add-on.

**Comment by shedman214** [comment]
Thank you

**Comment by shedman214** [comment]
I'm getting this error after i restarted HA. 
![image](https://github.com/user-attachments/assets/baf26448-2852-4609-942f-9f84b0845661)
![image](https://github.com/user-attachments/assets/a2649be2-600a-43a0-a03a-372203adce0a)

**Comment by SavageCore** [comment]
That means rest_command is already defined somewhere else, have a search for it and just copy and paste the rest of the block without rest_command, making sure it's indented one, currently it isn't.

**Comment by shedman214** [comment]
@SavageCore I think i fixed it right?
![image](https://github.com/user-attachments/assets/aa80f9ea-ce08-4535-9002-96aa06c9c85d)

**Comment by SavageCore** [comment]
Yes, that looks better, you can verify it with a site like https://www.yamllint.com/

`rest` needs renaming back to `rest_command`

**Comment by shedman214** [comment]
> Yes, that looks better, you can verify it with a site like https://www.yamllint.com/
> 
> `rest` needs renaming back to `rest_command`

That worked

**Comment by shedman214** [comment]
@SavageCore is this correct or how do I add this part? 
![image](https://github.com/user-attachments/assets/f3c7d422-8c67-4043-a753-3d0c054389cc)
![image](https://github.com/user-attachments/assets/fad84c08-376c-4be0-93c6-999d7411f2f0)

**Comment by SavageCore** [comment]
That is correct yes, don't change those, they're HA events from the [shopping list](https://www.home-assistant.io/integrations/shopping_list/#using-in-automations) add-on.

You can change the `alias`, that's just a name for your reference. `id` can also be changed but they must be unique.

**Comment by shedman214** [comment]
@SavageCore Final automation, also which shopping list would I add to from home assistant? example would be if I want to add bread to my shopping list from HA?
```
alias: Shopping list
description: ""
triggers:
  - trigger: event
    event_type: shopping_list_updated
    event_data:
      action: add
    id: add to list
    alias: add list
  - trigger: event
    event_type: shopping_list_updated
    event_data:
      action: update
    id: update list
    alias: update list
  - trigger: event
    event_type: shopping_list_updated
    event_data:
      action: remove
    id: remove from list
    alias: remove list
conditions: []
actions:
  - alias: add list
    if:
      - condition: trigger
        id:
          - add to list
    then:
      - action: rest_command.add_shopping_list_item
        metadata: {}
        data: {}
  - alias: update list
    if:
      - condition: trigger
        id:
          - update list
    then:
      - action: rest_command.complete_shopping_list_item
        metadata: {}
        data: {}
  - alias: remove list
    if:
      - condition: trigger
        id:
          - remove from list
    then:
      - action: rest_command.remove_shopping_list_item
        metadata: {}
        data: {}
mode: single
```
